name: Deployment

on:
  push:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/nikkikorzh/frontend-action-deploy:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-web-app-lab9
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
